# Generated by Django 2.2.1 on 2019-07-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='yourstar.StarType'),
        ),
    ]
