# Generated by Django 2.2.1 on 2019-07-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0002_auto_20190726_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yourstar.StarType'),
        ),
    ]
