# Generated by Django 2.2.1 on 2019-08-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0004_auto_20190814_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorename',
            name='type',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='yourstar.StarType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='star_list', to='yourstar.Event'),
        ),
    ]
