# Generated by Django 2.2.1 on 2019-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0011_auto_20190817_0123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
