# Generated by Django 2.2.1 on 2020-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0012_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorename',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='starscores',
            name='feed',
            field=models.TextField(blank=True),
        ),
    ]
