# Generated by Django 2.2.1 on 2020-02-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0015_remove_evaluation_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='starscores',
            name='star',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_list', to='yourstar.Star'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_score_list', to='yourstar.Star'),
        ),
    ]
