# Generated by Django 2.2.1 on 2020-02-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourstar', '0023_auto_20200222_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='youruser',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
